### ISSUE TITLE
Twig integration only works if your template files have a .twig extension

### ISSUE THREAD

**Issue by allmarkedup** [mheap/Silex-Assetic#11]
It would be great if it could be configured to scan the Twig paths for any files, not just those that use a .twig extension - I've got a lot of legacy projects that have just .html extensions for their filenames and it's  not currently compatible with them.

I'll try and put together a pull request for this when I have a few spare seconds :-)

**Comment by wesleyvicthor** [comment]
@allmarkedup not sure about this once twig will only interpret files ending with the extension .twig.

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
