### ISSUE TITLE
Faster auto_dump_assets with Twig during development

### ISSUE THREAD

**Issue by arsfeld** [mheap/Silex-Assetic#34]
Assetic default implementation for `auto_dump_assets` was too slow for me, every request would take 3 to 6 seconds in a high-end machine. I figured out the problem was that Assetic was loading all Twig templates every request to dump every single asset in the project, where in fact I only needed dumped the assets used during that request.
So I disabled auto_dump_assets and made my own, which does just that. 

Not sure it fits the default code well, but works great for me and might help someone else with the same issue. I've put under a gist in https://gist.github.com/arsfeld/55d138566c1412e056ba

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
