### ISSUE TITLE
Using asset caching with Twig

### ISSUE THREAD

**Issue by kwisatz** [mheap/Silex-Assetic#37]
I'm trying to cache dumped assets and I'm using the Twig extension for managing the assets:

``` php
{% stylesheets
        '../vendor/twbs/bootstrap/less/bootstrap.less'
        '../vendor/eonasdan/bootstrap-datetimepicker/src/less/bootstrap-datetimepicker.less'
        filter='unless,?cssmin' output='/css/project.css' %}
        <link href="{{ asset_url }}" type="text/css" rel="stylesheet"/>
    {% endstylesheets %}
```

I have not used the _assetic.asset_manager_ inside my app.php file, since, as I understood it, you can use either that, or the Twig Bridge. Or do I need to use the asset manager in order to make use of caching?

Could anyone help me out with an example of how I would get it to work using the Twig extension (or just tell me it can't be done)? Thanks.

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
