### ISSUE TITLE
Asset output path using variable

### ISSUE THREAD

**Issue by cjmarkham** [mheap/Silex-Assetic#39]
Sorry if this isn't the right place.

I am trying to use a variable to define the output path in Twig as per the symfony assetic docs.

```
{% javascripts 
    'js/dom.js'
    filter="yui_js"
    output="{root}concat/concat.js"
    vars=["root"]
%}
```

However I am unsure about how to set this variable using the service provider.

Any tips?

**Comment by ecentinela** [comment]
I'm trying to use this feature too, but I cannot find the way?
@cjmarkham  did you found a way?
@mheap can you help with this?

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
