### ISSUE TITLE
Pimple integration

### ISSUE THREAD

**Issue by thormug** [mheap/Silex-Assetic#47]
Hi, i downloaded this provider today and encounter a problem probably due to Pimple.

Right after register the provider, i have an error : 

*Fatal error: Interface 'Pimple\ServiceProviderInterface' not found in [...]/vendor/mheap/silex-assetic/src/SilexAssetic/AsseticServiceProvider.php on line 23*

Pimple is not set as required in composer.json and i don't know which package i have to download.

Thanks you very much

**Comment by mheap** [comment]
https://packagist.org/packages/pimple/pimple

**Comment by thormug** [comment]
Thanks for your answer. I still have problemens due to the fact i have silex in 1.2.3 (with require pimple 1) and pimple 3 next to it.

*Problem 1
    - silex/silex v1.2.3 requires pimple/pimple ~1.0 -> no matching package found.
    - silex/silex v1.2.3 requires pimple/pimple ~1.0 -> no matching package found.
    - Installation request for silex/silex 1.2.3 -> satisfiable by silex/silex[v1.2.3].*

But with Silex 2.0-dev, pimple 3 is required. I need to change some code (especially with the UrlGeneratorServiceProvider which disapeared in this version)

Thanks, i close this issue because the original problem is solved, and the second one is not related to Silex-Assetic

**Comment by mheap** [comment]
@thormug You can depend on version 1.0.4 which is Pimple 1.0 compatible

**Comment by thormug** [comment]
Good idea, i will do that waiting for the silex 2.0 release
Thanks !
