### ISSUE TITLE
Fatal error: Interface 'Pimple\ServiceProviderInterface' not found

### ISSUE THREAD

**Issue by cierzniak** [mheap/Silex-Assetic#49]
Hi, I've problem with Silex-Assetic. After install with composer I get just something like it:

Fatal error: Interface 'Pimple\ServiceProviderInterface' not found in path/to/silex/vendor/mheap/silex-assetic/src/SilexAssetic/AsseticServiceProvider.php on line 23

{main}( )   ../index.php:0
spl_autoload_call ( )   ../index.php:17
Composer\Autoload\ClassLoader->loadClass( ) ../index.php:17
Composer\Autoload\includeFile( )    ../ClassLoader.php:301
include( 'path/to/silex/vendor/mheap/silex-assetic/src/SilexAssetic/AsseticServiceProvider.php' )   ../ClassLoader.php:412

Even demo does not work properly.

**Comment by sivolobov** [comment]
If you use Silex "**1.***" you should use version that starts with "**1.**". Because version 2 is for Silex 2 that have another file structure.

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
