### ISSUE TITLE
Call to undefined method Twig_Loader_Filesystem::getSource()

### ISSUE THREAD

**Issue by furester** [mheap/Silex-Assetic#53]
> Uncaught Exception Error: "Call to undefined method Twig_Loader_Filesystem::getSource()" at vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigResource.php line 35 {"exception":"[object] (Error(code: 0): Call to undefined method Twig_Loader_Filesystem::getSource() at vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigResource.php:35

with last libraries update I get this error, to solve i copied this lib and changed composer.json to use latest `kriswallsmith/assetic` dev version and `twig` 2.0 like this:

> "minimum-stability": "dev",
> "require": {
>         "php": ">=5.3.0",
>         "kriswallsmith/assetic": "dev-master",
>         "symfony/finder": "*"
>     },
>     "require-dev": {
>         "silex/silex": "~2.0@dev",
>         "twig/twig": "~1.2",
>         "phpunit/phpunit": "~3.7.10"
>     },
>     "suggest": {
>         "twig/twig": "^2.0"
>     },

if you prefer and explain me how to do i could do a pull request. thanks.

**Comment by mheap** [comment]
This repo has been archived as the provider is no longer supported. Please feel free to fork if you require ongoing changes
